soil_discover_homepage:
    path:     /discover/{entity_uri}
    defaults: {       _controller: soil_discover.controller.discover_controller:discoverAction, expected_class: false }
    requirements:
        entity_uri: .+
