services:
    soil_discover.controller.discover_controller:
        class: Soil\DiscoverBundle\Controller\DefaultController
        arguments: [@soil_discover.service.resolver, @templating]

    soil_discover.service.resolver:
        class: Soil\DiscoverBundle\Service\Resolver
        arguments: [@soil_discover.entity_factory, %semantic_namespaces%]
        calls:
            - [setLogger, [@logger]]
        tags:
            - { name: monolog.logger, channel: queue }

    soil_discover.entity_factory:
        class: Soil\DiscoverBundle\Entity\Factory\EntityFactory
        arguments: [%entity_classes%]
        calls:
            - [setLogger, [@logger]]
        tags:
            - { name: monolog.logger, channel: queue }